### ISSUE TITLE
Inaccurate rockspec information should be fixed

### ISSUE THREAD

**Issue by hsluoyz** [tom2nonames/lua-resty-casbin-adapter#1]
Like:

![图片](https://user-images.githubusercontent.com/3787410/212478333-a90d2cdc-6da8-4b44-9374-0c379c5f82a0.png)

**Comment by hsluoyz** [comment]
@tom2nonames

**Comment by transtone** [comment]
https://luarocks.org/modules/chaowu17/resty-casbin-adapter

`luarocks install resty-casbin-adapter`

**Comment by tom2nonames** [comment]
fixed.
