### ISSUE TITLE
AddPolicy error

### ISSUE THREAD

**Issue by transtone** [tom2nonames/lua-resty-casbin-adapter#3]
can't use `:` in act
```lua
      e:AddPolicy({"eve", "data3", "write:one"})
```
it will get `INSERT INTO casbin_rule  (ptype, v0, v1, v2) VALUES ('p', 'eve', 'data3', 'write'null'')`

The error is from a function named `parse_sql_bind_params`. it has a regMatch.
```lua
    local regex = [[(?<str>:(?<param>([1-9]|[a-z]|[A-Z]|_){1,}))]]
    local it,err = ngx_re_gmatch(sql, regex)
```

why do this? how to avoid it ?

**Comment by hsluoyz** [comment]
@tom2nonames

**Comment by transtone** [comment]
the orig sql is : `INSERT INTO :table_name  (ptype, v0, v1, v2) VALUES ('p', 'eve', 'data3', 'write:one')`

the regMatch will find the `:table_name` and replace it to `casbin_rule`.

it can update the regex to avoid match `:` in `' '`

**Comment by transtone** [comment]
对源码做了调整，临时先用着：
1. 将 `'` 加入匹配
2. 排除末尾为 `'` 的项

```lua
    local regex = [[(?<str>:(?<param>([1-9]|[a-z]|[A-Z]|_|'){1,}))]]
    local it,err = ngx_re_gmatch(sql, regex)
    if not it then
        log.error( "gmatch error: ", err)
        return
    end
    local parse_params = {}

    while true do
        local m, err = it()
        if err then
            log.error( "gmatch error: ", err)
            return
        end

        if not m or string.sub(m['str'], -1) == "'" then
            break
        end

        -- found a match
        t_insert( parse_params, { str = m['str'], val = m['param'] } )
    end
```

https://gitee.com/gridsoft/lua-resty-casbin-adapter
